# Generated by Django 3.2.15 on 2023-09-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230902_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
