# Generated by Django 3.2.15 on 2023-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('people_number', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Брони',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
