# Generated by Django 3.2.15 on 2023-09-13 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='time_register',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 9, 27, 35, 140404)),
        ),
    ]
