# Generated by Django 3.2.15 on 2023-09-13 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_users_time_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='time_register',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
