# Generated by Django 3.2.15 on 2023-09-13 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_users_time_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.menucategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description_product',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_product',
            field=models.CharField(max_length=64, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo_product',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='description',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales_product', verbose_name='Фотография продукта'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product_name',
            field=models.CharField(max_length=64, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.CharField(max_length=15, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='people_number',
            field=models.PositiveIntegerField(verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time',
            field=models.CharField(max_length=5, verbose_name='Время брони'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_register',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда пришла бронь'),
        ),
    ]
