# Generated by Django 3.2.15 on 2023-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_users_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='comment',
            field=models.TextField(default=None, verbose_name='Комментарий пользователя'),
        ),
    ]
