# Generated by Django 3.2.15 on 2023-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_users_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='comment',
            field=models.TextField(default=None, null=True, verbose_name='Комментарий пользователя'),
        ),
    ]
